import type { SiteContent } from "./types";

export const en: SiteContent = {
  localeName: "English",
  nav: { overview: "Inside SoulRise", organizers: "For organizers", earlyAccess: "Join early access" },
  common: { home: "Back to home", earlyAccess: "Early access", appLink: "Open in the app", support: "Support", application: "Organizer application", platform: "SoulRise", faq: "Questions & answers", optional: "Optional" },
  home: {
    hero: { eyebrow: "The event starts long before you arrive", lines: ["Discover events.", "Connect with people.", "Experience more together."], body: "Find your next event, meet people who share your energy, and stay connected long after it ends.", primary: "Join early access", secondary: "I organize events" },
    pillarsTitle: "It’s not only where you go. It’s who you meet and what stays with you.",
    pillarsIntro: "SoulRise turns an event from a date on the calendar into something you can feel part of.",
    pillars: [
      { number: "01", title: "Find somewhere you truly want to be", body: "Discover events around what moves you, not only what makes the most noise." },
      { number: "02", title: "Know who is behind the event", body: "Follow organizers and people with similar taste, and see where they are heading next." },
      { number: "03", title: "Stay close to the moment", body: "Talk, share, and keep the connection going before, during, and after the event." },
      { number: "04", title: "Arrive with everything ready", body: "Your ticket, location, and important updates are there right when you need them." },
    ],
    preview: { eyebrow: "Inside SoulRise", title: "A feel for what’s ahead", body: "We’ll share a real look at the app here soon, from the first discovery to the ticket at the door.", slots: ["Find your next event", "Know before you go", "See what’s happening", "Your tickets", "A home for organizers"], placeholder: "A real app preview will appear here", comingLabel: "Opening gradually" },
    value: { eyebrow: "What changes for you", title: "Easier choices. A warmer arrival. A connection that lasts.", items: ["Find nights and gatherings that genuinely fit you", "Arrive already feeling part of what is happening", "Keep the people and organizers you loved close", "Reach your ticket and details without digging for them"] },
    organizer: { eyebrow: "For organizers", title: "The relationship with your audience can last beyond one event.", body: "SoulRise helps people discover your work, follow what you create, and stay close between one event and the next.", items: ["Give your production a clear presence", "Publish and manage events", "Keep attendees up to date", "Build an ongoing audience relationship", "Use paid ticketing once approved"], note: "We open organizer access gradually and review every application personally. Paid events may need an additional approval step.", cta: "Apply as an organizer" },
    access: { eyebrow: "Early access", title: "SoulRise is opening gradually. Be there from the start.", body: "We’re welcoming our first users and organizers now. Public download links will appear here as access opens more widely.", user: "Join early access", organizer: "Apply as an organizer" },
    faqTitle: "A few things you may be wondering", faqs: [
      { q: "What is SoulRise?", a: "An app that brings events, people, and organizers closer—from the first discovery to long after the event ends." },
      { q: "Who is it for?", a: "For people who love to go out, discover, and connect—and for organizers who want a real, lasting relationship with their audience." },
      { q: "Can organizers publish events yet?", a: "You can apply now. We review each application and open access gradually." },
      { q: "Where will my tickets be?", a: "When ticketing is active for an event, your ticket and event details will be together in the app." },
      { q: "How do I apply as an organizer?", a: "Fill out the short organizer form. It is ready to be connected, but no details are sent yet." },
      { q: "Can I download the app now?", a: "SoulRise is opening to its first groups now. Download links will appear here as access expands." },
    ],
  },
  organizers: {
    title: "Build a relationship that lasts beyond one event.",
    lead: "SoulRise gives your production a home people can discover, follow, and return to—before the next event and after it.",
    capabilities: ["A clear presence for your production or business", "Event publishing and management", "Updates for people planning to attend", "Paid ticketing after review and approval"],
    processTitle: "It starts with a short introduction",
    process: [{ title: "Tell us about your work", body: "Share your contact details and a little about the events you create." }, { title: "We get to know you", body: "We review the application personally and check whether access fits the current rollout." }, { title: "We take the next step", body: "If approved, we’ll help prepare your presence and events. Publishing paid events may need another approval." }],
    note: "Submitting an application does not guarantee acceptance or paid-ticket access. During early access, capabilities open gradually.",
    formTitle: "Nice to meet you",
    formIntro: "This short form collects only what helps us understand who you are and what you create. It is ready to be connected, but no details are sent yet.",
    fields: { fullName: "Full name", businessName: "Production or business name", phone: "Phone", email: "Email", website: "Instagram or website (optional)", eventType: "What kind of events do you produce?", note: "Tell us a little about your work", privacy: "I’ve read the temporary privacy notice" },
    submit: "Check my application", success: "Everything looks good. The form is ready to be connected; for now, no details are sent or stored.", required: "Please fill in this field", invalidEmail: "Check that the email address is complete and valid", privacy: "Please acknowledge this before continuing",
  },
  support: { title: "Let’s make things clearer.", lead: "SoulRise is opening gradually. We’ve gathered the essentials here and will add more as access expands.", items: [{ title: "Using the app", body: "Short guides for access, everyday use, and common issues will appear here ahead of the wider opening." }, { title: "Deleting an account", body: "The approved way to request account deletion will be published here before the process goes live." }, { title: "Tickets and refunds", body: "Terms can differ by event. Accurate information will appear with the event and in the approved support guidance." }, { title: "Organizer support", body: "Ready to begin? Start with the organizer application. A personal support channel will follow." }], contactTitle: "Want to talk to us?", contactBody: "Our official support channel is still being prepared. We’ll publish a verified way to reach us here as soon as it is ready." },
  legal: { privacyTitle: "Privacy policy", termsTitle: "Terms of use", notice: "The approved legal text is being prepared and will appear here before the public opening.", intro: "We want this information to be clear and accurate. We won’t publish partial commitments before the wording has been legally reviewed and matched to the service that will actually be live.", sections: [{ title: "What you’ll find here", body: "The approved document will clearly explain what information is relevant to the service, how it is handled, how to contact us, and the rights and responsibilities involved." }, { title: "What remains before launch", body: "Before access opens more widely, we’ll add approved legal wording, official contact details, and a final check against the capabilities available at that time." }] },
  open: { title: "The direct path to the app is almost ready.", body: "We’re preparing a safe link that opens SoulRise directly. Until it is verified, this page keeps you on the website and never redirects automatically.", note: "Direct opening will go live only after the website and app links are tested on real devices." },
  download: { title: "SoulRise is opening gradually.", body: "We’re welcoming our first users and organizers now. Official download links will appear here as the app opens more widely.", note: "Verified store links and a scannable QR code will live here when they are ready." },
  footer: { line: "Discover events. Connect with people. Experience more together.", privacy: "Privacy", terms: "Terms", support: "Support", organizers: "For organizers", rights: "All rights reserved." },
};
