import type { SiteContent } from "./types";

export const en: SiteContent = {
  localeName: "English", nav: { overview: "Platform", organizers: "For organizers", earlyAccess: "Request early access" }, common: { home: "Back to home", learnMore: "Learn more", temporary: "Temporary content" },
  home: {
    hero: { eyebrow: "Events, people, and community in one place", lines: ["Discover events.", "Connect with people.", "Experience more together."], body: "SoulRise brings event discovery, people and organizers, social moments, tickets, and essential event information together in one app.", primary: "Request early access", secondary: "I organize events" },
    pillarsTitle: "More than an event. An experience that starts before and stays after.", pillarsIntro: "Everything you need to find what is next, arrive informed, and stay connected.", pillars: [{ number: "01", title: "Discover events", body: "Find experiences that fit your interests and see what is happening around you." }, { number: "02", title: "Connect with people and organizers", body: "Follow the people and communities you care about and discover what they create." }, { number: "03", title: "Share moments and stay connected", body: "Be part of the conversation before, during, and after an event." }, { number: "04", title: "Keep everything together", body: "Tickets, event details, and important updates in one accessible place." }],
    preview: { eyebrow: "Product experience", title: "A closer look at the app", body: "This area is ready for approved product screenshots. These frames do not depict fictional UI.", slots: ["Discovery & search", "Event details", "Community feed", "Ticket wallet", "Organizer tools"], placeholder: "Reserved for approved screenshot" },
    value: { eyebrow: "For you", title: "Less searching. More moments worth remembering.", items: ["Find experiences that fit your interests", "Stay connected before, during, and after an event", "Follow people and organizers that matter to you", "Keep tickets and event details in one place"] },
    organizer: { eyebrow: "For organizers", title: "Build a presence. Grow a community. Create what is next.", body: "SoulRise gives organizers a place to present their work, create and manage events, and communicate with attendees.", items: ["Apply for organizer access", "Build a public organizer presence", "Create and manage events", "Communicate with attendees", "Use ticketing tools when eligible and approved"], note: "Applications are reviewed. Paid-ticket access may require additional approval and payment readiness.", cta: "Apply as an organizer" },
    access: { eyebrow: "Early access", title: "SoulRise is still taking shape — be part of the beginning.", body: "Public release and app-store availability are not live yet. For now, express interest or apply as an organizer.", user: "I want early access", organizer: "Organizer application" },
    faqTitle: "Frequently asked questions", faqs: [{ q: "What is SoulRise?", a: "An app-based platform for discovering events, connecting with people and organizers, community interaction, and keeping tickets and information together." }, { q: "Who is SoulRise for?", a: "People looking for experiences and communities, and organizers who want to build a presence and manage events." }, { q: "Can organizers publish events?", a: "Organizers can apply. Organizer access is provided after review and approval." }, { q: "Where are tickets stored?", a: "When ticketing is available for an event, tickets and event details are kept together in the app." }, { q: "How can I apply as an organizer?", a: "Complete the form on the organizer page. At this stage it is a demo and sends no information." }, { q: "Is the app publicly available yet?", a: "Not yet. The website is in early-access mode and does not show unverified store links." }]
  },
  organizers: { title: "Your events. Your community. One place to grow.", lead: "Build a presence for your brand or production, create events, and stay connected with your audience — subject to review and approval.", capabilities: ["Organizer page and presence", "Event creation and management", "Attendee updates and communication", "Ticketing tools when eligible and approved"], processTitle: "How it works", process: [{ title: "Apply", body: "Share a few basic details about you and the events you create." }, { title: "Review", body: "Each application is reviewed for fit and readiness." }, { title: "Move forward together", body: "Once approved, prepare your presence and events. Paid selling requires further readiness and approval." }], note: "Approval is not instant and selling is not guaranteed. Capabilities open according to rollout stage, fit, and payment readiness.", formTitle: "Apply for organizer access", formIntro: "This is a front-end demo only. Your details will not be sent or stored.", fields: { fullName: "Full name", businessName: "Production or business name", phone: "Phone", email: "Email", website: "Instagram or website", eventType: "Event type", note: "Tell us briefly about your work", privacy: "I acknowledge the temporary privacy notice" }, submit: "Submit application (demo)", success: "The form is valid. In demo mode, no information was sent or stored.", required: "This field is required", invalidEmail: "Enter a valid email address", privacy: "Acknowledge this item to continue" },
  support: { title: "How can we help?", lead: "The full support center will arrive later. For now, these are the main areas being prepared.", items: [{ title: "General help", body: "Usage, app-access, and FAQ guidance will be added before public release." }, { title: "Account deletion", body: "Approved account deletion request guidance will appear here before the process is connected." }, { title: "Tickets and refunds", body: "Support policies and processes depend on the event and organizer. Approved information will replace this placeholder." }, { title: "Organizer support", body: "Organizers can start with the application page. A dedicated support channel will be configured later." }], contactTitle: "Contact", contactBody: "Official contact details have not been configured. Do not send personal information until a verified support channel appears here." },
  legal: { privacyTitle: "Privacy policy", termsTitle: "Terms of use", notice: "This is not final legal copy and is not production-ready. Approved legal content must replace it before launch.", intro: "For now, this page provides a clear and accessible location for the future approved document without creating commitments that have not been decided.", sections: [{ title: "What will be covered", body: "After legal approval, the final document will describe relevant data and processes, official contacts, and applicable rights or obligations." }, { title: "Before launch", body: "Complete legal review, configure official contact details, and confirm the document accurately matches the product and services that are actually enabled." }] },
  open: { title: "Open SoulRise", body: "A safe general link for opening SoulRise is not configured yet. This page does not launch the app or redirect automatically.", note: "Support will be enabled only after general domain and app links are verified." }, download: { title: "SoulRise is in early access", body: "The app is not presented here as publicly downloadable yet. Official store links will be added only after release is verified.", note: "Verified store links and an optional QR code can appear here in the future." },
  footer: { line: "Discover events. Connect with people. Experience more together.", privacy: "Privacy", terms: "Terms", support: "Support", organizers: "Organizers", rights: "All rights reserved." }
};
